apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-notifications-service
spec:
  project: default
  source:
    repoURL: "https://github.com/Nimrod-s-weather-app/weather-notifications-service.git"
    targetRevision: main
    path: "k8s"  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
